//ACTUALIZADO
export const TURNOS = [
  "1",
  "2",
  "3",
  "4",
  "Mixto"
]
//ACTUALIZADO
export const JEFES_DE_AREA = [
  "OCHOA VELAZQUEZ PAMELA",
  "BONILLA HERNANDEZ ADRIANA BEATRIZ",
  "BRAVO GARCIA JESUS FERNANDO",
  "CABRERO BOO MANUEL ALBERTO",
  "ESQUIVEL MATA ARIADNA NAYELY",
  "GARCIA JUAREZ XICOTENCATL",
  "GOMEZ SANCHEZ CARLOS ARIEL",
  "GOMEZ SANCHEZ CESAR",
  "HERNANDEZ GUDIÑO NOEMI",
  "HERNANDEZ RUIZ MIGUEL ANGEL",
  "INFANTE VAZQUEZ IVAN",
  "PEREZ BAUTISTA EDGAR",
  "SALINAS ORTIZ ANA ERIKA",
  "TERRAZAS MARTINEZ JAIME",
  "VIÑOLAS GONZALEZ JOSE LUIS"
]

export const EVALUADORES_DESEMPENO = [
  "OCHOA VELAZQUEZ PAMELA",
  "BIBIANO GARCIA FLOR",
  "BONILLA HERNANDEZ ADRIANA BEATRIZ",
  "BRAVO GARCIA JESUS FERNANDO",
  "CABRERO BOO MANUEL ALBERTO",
  "GALLARDO DIAZ CIUNELY YETZABEL",
  "CORONA ARCE LILIANA",
  "DIAZ GUTIERREZ JOSE GUADALUPE",
  "ESQUIVEL MATA ARIADNA NAYELY",
  "FLORES IBARRA VICTOR MANUEL",
  "GARCIA JUAREZ XICOTENCATL",
  "GOMEZ SANCHEZ CARLOS ARIEL",
  "GOMEZ SANCHEZ CESAR",
  "GUTIERREZ LOPEZ GUADALUPE",
  "HERNANDEZ CRUZ JORGE",
  "HERNANDEZ GARCIA JOVANIC TOMAS",
  "HERNANDEZ GUDIÑO NOEMI",
  "HERNANDEZ RUIZ MIGUEL ANGEL",
  "INFANTE VAZQUEZ IVAN",
  "JUAREZ HERNANDEZ SERGIO RICARDO",
  "MARTINEZ COBOS OMAR",
  "OCHOA ORTUÑO JOSE MA.",
  "ORTIZ OLVERA JUAN FIDEL",
  "PEREZ BAUTISTA EDGAR",
  "PEREZ SAMANIEGO ISRAEL",
  "RUEDA MUÑOZ FRANCISCO",
  "SALINAS ORTIZ ANA ERIKA",
  "SIXTOS PINEDA LUIS ANGEL",
  "TERRAZAS MARTINEZ JAIME",
  "VALDIVIA FRANCO CARLOS ALAIN",
  "VILLAMAR HINOJOSA DEISY",
  "LUNA SANDOVAL ISRAEL",
  "VIÑOLAS GONZALEZ JOSE LUIS",
]

export const EVALUADORES_PUESTO: Record<string, string> = {
  "OCHOA VELAZQUEZ PAMELA": "COORDINADOR DEL SGI",
  "ALVARADO FRAGOSO JORGE ALBERTO": "SUPERVISOR DE PRODUCCIÓN D",
  "BIBIANO GARCIA FLOR": "SUPERVISOR DE PRODUCCIÓN A",
  "BONILLA HERNANDEZ ADRIANA BEATRIZ": "GERENTE DE RECURSOS HUMANOS",
  "BRAVO GARCIA JESUS FERNANDO": "JEFE DE MANTENIMIENTO",
  "CABRERO BOO MANUEL ALBERTO": "COORDINADOR DE RPS",
  "CHONG ALTUZAR JOSE ANTONIO": "SUPERVISOR DE PRODUCCIÓN D",
  "CORONA ARCE LILIANA": "JEFE DE LOGISTICA",
  "DIAZ GUTIERREZ JOSE GUADALUPE": "SUPERVISOR DE PRODUCCIÓN C",
  "INFANTE VAZQUEZ IVAN": "GERENTE DE CALIDAD",
  "ESQUIVEL MATA ARIADNA NAYELY": "JEFE DE METROLOGÍA",
  "FLORES IBARRA VICTOR MANUEL": "SUPERVISOR DE PRODUCCIÓN B",
  "GARCIA JUAREZ XICOTENCATL": "JEFE DE ALMACÉN",
  "GOMEZ SANCHEZ CARLOS ARIEL": "GERENTE DE PRODUCCIÓN",
  "GOMEZ SANCHEZ CESAR": "JEFE DE TALLER DE MOLDES",
  "GUTIERREZ LOPEZ GUADALUPE": "SUPERVISOR DE ACABADOS - GP12 B",
  "HERNANDEZ CRUZ JORGE": "SUPERVISOR DE MONTAJE",
  "HERNANDEZ GARCIA JOVANIC TOMAS": "SUPERVISOR DE PRODUCCIÓN D",
  "HERNANDEZ GUDIÑO NOEMI": "JEFE DE RECURSOS HUMANOS",
  "HERNANDEZ RUIZ MIGUEL ANGEL": "DIRECTOR DE PLANTAS",
  "JUAREZ HERNANDEZ SERGIO RICARDO": "JEFE DE PRODUCCIÓN",
  "MARTINEZ COBOS OMAR": "SUPERVISOR DE PRODUCCIÓN D",
  "OCHOA ORTUÑO JOSE MA.": "SUPERVISOR DE PRODUCCIÓN B",
  "ORTIZ OLVERA JUAN FIDEL": "SUPERVISOR DE PRODUCCIÓN A",
  "PEREZ BAUTISTA EDGAR": "JEFE DEL SGI",
  "PEREZ SAMANIEGO ISRAEL": "SUPERVISOR DE PRODUCCIÓN C",
  "RUEDA MUÑOZ FRANCISCO": "JEFE DE PROCESOS",
  "SALINAS ORTIZ ANA ERIKA": "GERENTE DE PROYECTOS",
  "SIXTOS PINEDA LUIS ANGEL": "SUPERVISOR DE PRODUCCIÓN D",
  "TERRAZAS MARTINEZ JAIME": "GERENTE DE PLANTA",
  "VALDIVIA FRANCO CARLOS ALAIN": "SUPERVISOR DE PRODUCCIÓN C",
  "GALLARDO DIAZ CIUNELY YETZABEL": "SUPERVISOR DE ACABADOS - GP12 D",
  "VILLAMAR HINOJOSA DEISY": "SUPERVISOR DE PRODUCCIÓN C",
  "LUNA SANDOVAL ISRAEL": "SUPERVISOR DE PRODUCCIÓN D",
  "VIÑOLAS GONZALEZ JOSE LUIS": "DIRECTOR GENERAL",
}

//ACTUALIZADO
export const ESCOLARIDAD = [
  "PRIMARIA",
  "SECUNDARIA",
  "PREPARATORIA",
  "TECNICO",
  "LICENCIATURA",
  "INGENIERIA",
  "MAESTRIA",
  "DOCTORADO"
]

export const JEFES_DE_AREA_POR_DEPARTAMENTO: { [departamento: string]: string[] } = {
  "PRODUCCIÓN": [
    "GOMEZ SANCHEZ CARLOS ARIEL ",
  ],
  "MANTENIMIENTO": [
    "BRAVO GARCIA JESUS FERNANDO",
  ],
  "ALMACÉN": [
    "GARCIA JUAREZ XICOTENCATL",
  ],
  "RECURSOS HUMANOS": [
    "HERNANDEZ GUDIÑO NOEMI",
  ],
  "TALLER DE MOLDES": [
    "GOMEZ SANCHEZ CESAR",
  ],
  "SGI": [
    "OCHOA VELAZQUEZ PAMELA",
  ],
  "METROLOGÍA": [
    "ESQUIVEL MATA ARIADNA NAYELY",
  ],
  "PROYECTOS": [
    "SALINAS ORTIZ ANA ERIKA",
  ],
  "SISTEMAS": [
    "CABRERO BOO MANUEL ALBERTO",
  ],
    "CALIDAD": [
      "INFANTE VAZQUEZ IVAN",
  ],
}

export const DEPARTAMENTOS_EVALUADORES: Record<string, string[]> = {
  "Dirección": [
    "VIÑOLAS GONZALEZ JOSE LUIS",
    "HERNANDEZ RUIZ MIGUEL ANGEL",
  ],
  "Gerencia": [
    "TERRAZAS MARTINEZ JAIME",
  ],
  "Producción": [
    "GOMEZ SANCHEZ CARLOS ARIEL",
    "JUAREZ HERNANDEZ SERGIO RICARDO",
    "RUEDA MUÑOZ FRANCISCO",
    "BIBIANO GARCIA FLOR",
    "CHONG ALTUZAR JOSE ANTONIO",
    "DIAZ GUTIERREZ JOSE GUADALUPE",
    "FLORES IBARRA VICTOR MANUEL",
    "HERNANDEZ GARCIA JOVANIC TOMAS",
    "MARTINEZ COBOS OMAR",
    "OCHOA ORTUÑO JOSE MA.",
    "ORTIZ OLVERA JUAN FIDEL",
    "PEREZ SAMANIEGO ISRAEL",
    "SIXTOS PINEDA LUIS ANGEL",
    "VALDIVIA FRANCO CARLOS ALAIN",
    "VILLAMAR HINOJOSA DEISY",
    "LUNA SANDOVAL ISRAEL"
    ],
  "Montaje": [
    "HERNANDEZ CRUZ JORGE",
  ],
  "Acabados GP12": [
    "GUTIERREZ LOPEZ GUADALUPE",
    "GALLARDO DIAZ CIUNELY YETZABEL",
  ],
  "Recursos Humanos": [
    "BONILLA HERNANDEZ ADRIANA BEATRIZ",
    "HERNANDEZ GUDIÑO NOEMI",
  ],
  "Calidad": [
      "INFANTE VAZQUEZ IVAN",
  ],
  "Metrología": [
    "ESQUIVEL MATA ARIADNA NAYELY",
  ],
  "SGI": [
    "OCHOA VELAZQUEZ PAMELA",
    "PEREZ BAUTISTA EDGAR",
  ],
  "Mantenimiento": [
    "BRAVO GARCIA JESUS FERNANDO",
  ],
  "Almacén": [
    "GARCIA JUAREZ XICOTENCATL",
    ],
  "Logística": [
    "CORONA ARCE LILIANA",
  ],
  "Moldes": [
    "GOMEZ SANCHEZ CESAR",
  ],
  "Proyectos": [
    "SALINAS ORTIZ ANA ERIKA",
  ],
  "SISTEMAS": [
    "CABRERO BOO MANUEL ALBERTO",
    ],
}
