export interface CatalogoJerarquia {
  [departamento: string]: {
    areas: string[];
    puestos: string[];
  }
}
//ACTUALIZADO
export const CATALOGO_ORGANIZACIONAL: CatalogoJerarquia = {
  "PRODUCCIÓN": {
    areas: ["PRODUCCIÓN 1ER TURNO",
      "PRODUCCIÓN 2DO TURNO",
      "PRODUCCIÓN 3ER TURNO",
      "PRODUCCIÓN 4TO TURNO",
      "PRODUCCIÓN ADMINISTRATIVO",
      "PRODUCCIÓN MONTAJE"],
    puestos: ["GERENTE DE PRODUCCIÓN",
      "JEFE DE PRODUCCIÓN",
      "ASISTENTE DE PRODUCCIÓN A",
      "ASISTENTE DE PRODUCCIÓN B",
      "PLANEADOR DE PRODUCCIÓN",
      "SUPERVISOR DE PRODUCCIÓN A",
      "SUPERVISOR DE PRODUCCIÓN B",
      "SUPERVISOR DE PRODUCCIÓN C",
      "SUPERVISOR DE PRODUCCIÓN D",
      "OPERADOR DE MÁQUINA A",
      "OPERADOR DE MÁQUINA B",
      "OPERADOR DE MÁQUINA C",
      "OPERADOR DE MÁQUINA D",
      "AUXILIAR DE SCRAP A",
      "AUXILIAR DE SCRAP B",
      "AUXILIAR DE BÁSCULA A",
      "AUXILIAR DE BÁSCULA B",
      "AUXILIAR DE SUPERVISOR A",
      "AUXILIAR DE SUPERVISOR B",
      "CHECK LIST A",
      "CHECK LIST B",
      "MATERIALISTA A",
      "MATERIALISTA B",
      "PREPARADOR A",
      "PREPARADOR B",
      "CAPTURISTA RPS A",
      "CAPTURISTA RPS B",
      "JEFE DE PROCESO",
      "INGENIERO DE PROCESO A",
      "INGENIERO DE PROCESO B",
      "INGENIERO DE PROCESO C",
      "INGENIERO DE PROCESO D",
      "SUPERVISOR DE MONTAJE",
      "MONTADOR DE MOLDES A",
      "MONTADOR DE MOLDES B",
      "MONTADOR DE MOLDES C",
      "MONTADOR DE MOLDES D"]
  },//ACTUALIZADO
  "CALIDAD": {
    areas: ["A. CALIDAD 1ER TURNO",
      "A. CALIDAD 2DO TURNO",
      "CALIDAD ADMINISTRATIVO",
      "RESIDENTES DE CALIDAD"
    ],
    puestos: ["GERENTE DE CALIDAD",
      "JEFE DE CALIDAD",
      "INGENIERO DE CALIDAD A",
      "INGENIERO DE CALIDAD B",
      "INGENIERO DE CALIDAD C",
      "INSPECTOR DE CALIDAD A",
      "INSPECTOR DE CALIDAD B",
      "INSPECTOR DE CALIDAD C",
      "INSPECTOR DE CALIDAD D",
      "INSPECTOR RECIBO",
      "OPERADOR DE ACABADOS - GP12 A",
      "OPERADOR DE ACABADOS - GP12 B",
      "OPERADOR DE ACABADOS - GP12 C",
      "OPERADOR DE ACABADOS - GP12 D",
      "RESIDENTE DE CALIDAD A",
      "RESIDENTE DE CALIDAD B",
      "RESIDENTE DE CALIDAD C",
      "SUPERVISOR DE ACABADOS - GP12 A",
      "SUPERVISOR DE ACABADOS - GP12 B",
      "SUPERVISOR DE ACABADOS - GP12 C"]
  },//ACTUALIZADO
  "MANTENIMIENTO": {
    areas: ["MANTENIMIENTO"],
    puestos: ["AUXILIAR ADMINISTRATIVO DE MANTENIMIENTO",
      "AUXILIAR DE MANTENIMIENTO A",
      "AUXILIAR DE MANTENIMIENTO C",
      "JEFE DE MANTENIMIENTO",
      "TÉCNICO DE MANTENIMIENTO B",
      "TÉCNICO DE MANTENIMIENTO C",
      "TÉCNICO DE MANTENIMIENTO D",
      "TECNICO DE MANTENIMIENTO DE EDIFICIOS A",
      "TÉCNICO ESPECIALISTA DE MANTENIMIENTO A",
      "TÉCNICO ESPECIALISTA DE MANTENIMIENTO B"]
  },//ACTUALIZADO
  "ALMACÉN": {
    areas: ["ALMACÉN"],
    puestos: ["ALMACENISTA DE MATERIA PRIMA",
      "AUXILIAR ADMINISTRATIVO DE ALMACÉN A",
      "AUXILIAR ADMINISTRATIVO DE ALMACÉN B",
      "AUXILIAR ADMINISTRATIVO DE ALMACÉN C",
      "AUXILIAR DE ALMACÉN A",
      "AUXILIAR DE ALMACÉN B",
      "AUXILIAR DE ALMACÉN C",
      "AUXILIAR DE ALMACÉN D",
      "JEFE DE ALMACÉN"]
  },//ACTUALIZADO
  "RECURSOS HUMANOS": {
    areas: ["RECURSOS HUMANOS"],
    puestos: ["JEFE DE RECURSOS HUMANOS",
      "AUXILIAR DE RECURSOS HUMANOS",
      "AUXILIAR DE LIMPIEZA A",
      "AUXILIAR DE LIMPIEZA B",
      "ANALISTA DE CAPACITACIÓN",
      "ANALISTA DE RECLUTAMIENTO Y SELECCIÓN A",
      "ANALISTA DE RECLUTAMIENTO Y SELECCIÓN B",
      "ANALISTA DE SEGURIDAD E HIGIENE",
      "ANALISTA DE RECURSOS HUMANOS",
      "ASISTENTE DE RECURSOS HUMANOS",
      "COORDINADOR DE RECLUTAMIENTO Y SELECCIÓN"]
  },//ACTUALIZADO
  "TALLER DE MOLDES": {
    areas: ["MOLDES"],
    puestos: ["AUXILIAR ADMINISTRATIVO DE TALLER DE MOLDES",
      "TÉC. ESPECIALISTA DE MOLDES (JEFE)",
      "TÉCNICO DE MOLDES A",
      "TÉCNICO DE MOLDES B",
      "TÉCNICO DE MOLDES C",
      "TÉCNICO DE MOLDES D",
      "TÉCNICO DE MOLDES E"]
  },//ACTUALIZADO
  "SGI": {
    areas: ["SGI"],
    puestos: ["COORDINADOR DE SGI",
      "AUXILIAR DE SGI A",
      "AUXILIAR DE SGI B",
      "AUXILIAR DE SGI C"]
  },//ACTUALIZADO
  "METROLOGÍA": {
    areas: ["METROLOGÍA"],
    puestos: ["JEFE DE METROLOGÍA",
      "SUPERVISOR DE METROLOGÍA",
      "METRÓLOGO A",
      "METRÓLOGO B",
      "METRÓLOGO C",
      "AUXILIAR DE METROLOGÍA"]
  },//ACTUALIZADO
  "PROYECTOS": {
    areas: ["PROYECTOS"],
    puestos: ["GERENTE DE PROYECTOS",
      "AUXILIAR DE PROYECTOS",
      "LIDER DE COTIZACIONES",
      "INGENIERO DE PROYECTOS A",
      "INGENIERO DE PROYECTOS B",
      "INGENIERO DE PROYECTOS D",
      "LIDER DE PROYECTOS A",
      "LIDER DE PROYECTOS B",
      "LÍDER DE PROYECTOS C"]
  },//ACTUALIZADO
  "SISTEMAS": {
    areas: ["SISTEMAS"],
    puestos: ["COORDINADOR DE RPS",
      "AUXILIAR PROGRAMADOR"]
  },//ACTUALIZADO
  "LOGÍSTICA": {
    areas: ["LOGÍSTICA"],
    puestos: ["JEFE DE LOGÍSTICA",
      "SUPERVISOR DE LOGÍSTICA"]
  },//ACTUALIZADO
  "GERENCIA DE PLANTA": {
    areas: ["GERENCIA DE PLANTA"],
    puestos: ["GERENTE DE PLANTA"]
  } //ACTUALIZADO
}
//ACTUALIZADO
export const TURNOS = [
  "1",
  "2",
  "3",
  "4",
  "Mixto"
]
//ACTUALIZADO
export const JEFES_DE_AREA = [
  "AGUILLON RANGEL LIZBETH",
  "BONILLA HERNANDEZ ADRIANA BEATRIZ",
  "BRAVO GARCIA JESUS FERNANDO",
  "CABRERO BOO MANUEL ALBERTO",
  "CENOBIO HERNANDEZ JORGE ALBERTO",
  "ESQUIVEL MATA ARIADNA NAYELY",
  "GARCIA JUAREZ XICOTENCATL",
  "GOMEZ SANCHEZ CARLOS ARIEL",
  "GOMEZ SANCHEZ CESAR",
  "HERNANDEZ GUDIÑO NOEMI",
  "HERNANDEZ RUIZ MIGUEL ANGEL",
  "PEREZ BAUTISTA EDGAR",
  "SALINAS ORTIZ ANA ERIKA",
  "TERRAZAS MARTINEZ JAIME",
  "VIÑOLAS GONZALEZ JOSE LUIS"
]
//ACTUALIZADO
export const ESCOLARIDAD = [
  "PRIMARIA",
  "SECUNDARIA",
  "PREPARATORIA",
  "TECNICO",
  "LICENCIATURA",
  "INGENIERIA",
  "MAESTRIA",
  "DOCTORADO"
]